# Generated by Django 3.2.9 on 2021-11-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradiseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='img',
            field=models.ImageField(default='haris', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
